/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-common:src/main/java/web/selectitem.enum.vm.java
 */
package com.yourcompany.yourproject.web.domain.enums;

import java.util.ArrayList;
import java.util.List;

import javax.faces.model.SelectItem;

import org.springframework.stereotype.Component;

import com.yourcompany.yourproject.domain.enums.CivilityEnum;

/**
 * Helper to support the h:selectOneRadio and h:selectOneMenu for contactInfo.civility
 */
@Component
public class CivilityEnumItems {

    /**
     * Returns a list of SelectItem/CivilityEnum ready to use in a h:selectOneRadio and h:selectOneMenu tags
     */
    public List<SelectItem> getList() {
        List<SelectItem> result = new ArrayList<SelectItem>();
        for (CivilityEnum civility : CivilityEnum.values()) {
            result.add(new SelectItem(civility, civility.getLabel()));
        }

        return result;
    }
}
