/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-common:src/main/java/web/filter/ExceptionFilter.p.vm.java
 */
package com.yourcompany.yourproject.web.filter;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

/**
 * Simple Filter that redirects the user to an error page in case of exception. It also 
 * log the error and create an unique exception id to be displayed in the error page.
 */
public final class ExceptionFilter implements Filter {
    private static final Logger logger = Logger.getLogger(ExceptionFilter.class);

    @Override
    public void init(FilterConfig config) throws ServletException {
    }

    @Override
    public void doFilter(ServletRequest req, ServletResponse resp, FilterChain chain) throws IOException,
            ServletException {
        try {
            // chain...
            chain.doFilter(req, resp);
        } catch (Exception e) {
            // redirect to error page
            HttpServletRequest request = (HttpServletRequest) req;
            request.getSession().setAttribute("lastException", e);
            request.getSession().setAttribute("lastExceptionUniqueId", e.hashCode());

            logger.error("EXCEPTION unique id: " + e.hashCode(), e); // todo: better

            HttpServletResponse response = (HttpServletResponse) resp;
            // TODO: make it configurable in web.xml   
            // TODO: make it work with ajax request   
            response.sendRedirect("/pages/error.faces");
        }
    }

    @Override
    public void destroy() {
    }
}