/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ModelGenerator.e.vm.java
 */
package com.yourcompany.yourproject.service.more;

import java.util.*;

import com.yourcompany.yourproject.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.yourcompany.yourproject.domain.more.MoreTypesDemo;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class MoreTypesDemoGenerator {

    /**
     * Returns a new MoreTypesDemo instance filled with random values.
     */
    public MoreTypesDemo getMoreTypesDemo() {
        MoreTypesDemo moreTypesDemo = new MoreTypesDemo();

        // simple attributes follows
        moreTypesDemo.setNumberInt(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        moreTypesDemo.setNumberLong(ValueGenerator.getNumeric(java.lang.Long.class, "1"));
        moreTypesDemo.setNumberDouble(ValueGenerator.getNumeric(java.lang.Double.class, "1"));
        moreTypesDemo.setNumberFloat(ValueGenerator.getNumeric(java.lang.Float.class, "1"));
        moreTypesDemo.setNumberBigInteger(ValueGenerator.getNumeric(java.math.BigInteger.class, "1"));
        moreTypesDemo.setNumberBigDecimal(ValueGenerator.getNumeric(java.math.BigDecimal.class, "1"));
        moreTypesDemo.setDateJavaTemporalDate(new Date());
        moreTypesDemo.setDateJavaTemporalTimestamp(new Date());
        moreTypesDemo.setDateJoda(new org.joda.time.LocalDate());
        moreTypesDemo.setDateTimeJoda(new org.joda.time.LocalDateTime());
        return moreTypesDemo;
    }

}