/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/domain/ModelTest.e.vm.java
 */
package com.yourcompany.yourproject.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.yourcompany.yourproject.util.*;
import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.QueryHint;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import com.yourcompany.yourproject.domain.Address;
import com.yourcompany.yourproject.domain.Book;
import com.yourcompany.yourproject.domain.ContactInfo;
import com.yourcompany.yourproject.domain.Document;
import com.yourcompany.yourproject.domain.Role;

/**
 * Basic tests for Account
 */
public class AccountTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Account model = new Account();
        assertFalse(model.isPrimaryKeySet());
    }

    @Test
    public void isPrimaryKeySetReturnsTrue() {
        Account model = new Account();
        model.setAccountId(ValueGenerator.getUniqueString(32));
        assertNotNull(model.getAccountId());
        assertTrue(model.isPrimaryKeySet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Account.addressId ==> Address.addressId
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setHomeAddress() {
        Account many = new Account();

        // init
        Address one = new Address();

        one.setAddressId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));
        many.setHomeAddress(one);

        // make sure it is propagated properly
        assertNotNull(many.getAddressId());
        assertEquals(one, many.getHomeAddress());
        assertSame(many.getAddressId(), one.getAddressId());
        // now set it to back to null
        many.setHomeAddress(null);

        // make sure null is propagated properly
        assertNull(many.getHomeAddress());

        // make sure it is propagated on fk column as well
        assertNull(many.getAddressId());
    }

    //-------------------------------------------------------------
    // One to Many: SimpleOneToMany ACCOUNT.ACCOUNT_ID ==> BOOK.account_id
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // book.book <-- account.accounts
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addBook() {
        Account one = new Account();
        Book many = new Book();

        // init
        one.addBook(many);

        // make sure it is propagated
        assertTrue(one.containsBook(many));
        assertTrue(one.equals(many.getAccount()));

        // now set it to null
        one.removeBook(many);

        // make sure null is propagated
        assertFalse(one.containsBook(many));
        assertNull(many.getAccount());
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // document.document <-- account.accounts
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addDocument() {
        Account one = new Account();
        Document many = new Document();

        // init
        one.addDocument(many);

        // make sure it is propagated
        assertTrue(one.containsDocument(many));
        assertTrue(one.equals(many.getAccount()));

        // now set it to null
        one.removeDocument(many);

        // make sure null is propagated
        assertFalse(one.containsDocument(many));
        assertNull(many.getAccount());
    }

    //-------------------------------------------------------------
    // Pure Many to Many
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void manyToMany_addRole() {
        Account many1 = new Account();
        Role many2 = new Role();

        // add it
        many1.addRole(many2);

        // check it is propagated
        assertTrue(many1.containsRole(many2));
        // now let's remove it
        many1.removeRole(many2);

        // check it is propagated
        assertFalse(many1.containsRole(many2));
    }

    @Test
    public void toStringNotNull() {
        Account model = new Account();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingBusinessKey() {
        Account model1 = new Account();
        Account model2 = new Account();
        String username = ValueGenerator.getUniqueString(255);
        model1.setUsername(username);
        model2.setUsername(username);
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
        assertTrue(model1.hashCode() == model2.hashCode());
    }
}