/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/domain/ModelTest.e.vm.java
 */
package com.yourcompany.yourproject.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.yourcompany.yourproject.util.*;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import com.yourcompany.yourproject.domain.Account;

/**
 * Basic tests for Book
 */
public class BookTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Book model = new Book();
        assertFalse(model.isPrimaryKeySet());
    }

    @Test
    public void isPrimaryKeySetReturnsTrue() {
        Book model = new Book();
        model.setBookId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));
        assertNotNull(model.getBookId());
        assertTrue(model.isPrimaryKeySet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Book.accountId ==> Account.accountId
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setAccount() {
        Book many = new Book();

        // init
        Account one = new Account();

        one.setAccountId(ValueGenerator.getUniqueString(32));
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getAccountId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    @Test
    public void toStringNotNull() {
        Book model = new Book();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Book model1 = new Book();
        Book model2 = new Book();

        Integer bookId = ValueGenerator.getUniqueNumeric(Integer.class, "2147483647");
        model1.setBookId(bookId);
        model2.setBookId(bookId);

        model1.setTitle("d");
        model2.setTitle("d");

        model1.setNumberOfPages(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setNumberOfPages(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));

        model1.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        assertTrue(model1.isPrimaryKeySet());
        assertTrue(model2.isPrimaryKeySet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}