/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/support/package-info.p.vm.java
 */
/**
 * Specific utils or implementation used in relation with hibernate
 */
package com.yourcompany.yourproject.dao.hibernate;