/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.yourcompany.yourproject.dao;

import org.springframework.stereotype.Repository;
import com.yourcompany.yourproject.dao.AddressDao;

import com.yourcompany.yourproject.domain.Address;
import com.yourcompany.yourproject.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the Address DAO interface.
 */
@Repository
public class AddressDaoImpl extends HibernateGenericDao<Address, Integer> implements AddressDao {
    public AddressDaoImpl() {
        super(Address.class);
    }
}