/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.yourcompany.yourproject.dao;

import org.hibernate.Criteria;
import org.hibernate.criterion.Conjunction;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import com.yourcompany.yourproject.dao.DocumentDao;
import com.yourcompany.yourproject.dao.hibernate.HibernateUtil;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

import com.yourcompany.yourproject.domain.Account;
import com.yourcompany.yourproject.domain.Document;
import com.yourcompany.yourproject.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the Document DAO interface.
 */
@Repository
public class DocumentDaoImpl extends HibernateGenericDao<Document, String> implements DocumentDao {
    public DocumentDaoImpl() {
        super(Document.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed document but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(Document document, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(document, searchTemplate);

        // many-to-one: "account"
        // Note 1: If 'accountId' != null, no need to add a criteria as the current criteria 
        // already takes this property into account.
        // Note 2: By convention, if the example for "account" has no property set 
        // and "account" is not null we assume that you want a not null criteria. 
        if (document.getAccountId() == null && document.getAccount() != null) {
            criteria.add(Restrictions.isNotNull("account"));
            criteria.createCriteria("account").add(
                    HibernateUtil.constructExample(document.getAccount(), searchTemplate));
        }

        return criteria;
    }
}