/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/SearchForm.e.vm.java
 */
package com.yourcompany.yourproject.web.domain;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.primefaces.model.SortOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.yourcompany.yourproject.dao.support.SearchTemplate;
import com.yourcompany.yourproject.dao.support.SearchMode;
import com.yourcompany.yourproject.domain.Book;
import com.yourcompany.yourproject.service.BookService;
import com.yourcompany.yourproject.web.domain.support.GenericSearchForm;

/**
 * SearchForm for BookService
 */
@Component
@Scope("session")
public class BookSearchForm extends GenericSearchForm<Book> implements Serializable {
    private static final long serialVersionUID = 1L;
    // make it static to avoid http://jira.springframework.org/browse/SWF-1224
    private static BookService bookService;

    private Book book = new Book();
    private SearchTemplate searchTemplate = new SearchTemplate().setSearchMode(SearchMode.ANYWHERE);

    @Autowired
    public BookSearchForm(BookService instance) {
        if (bookService == null) {
            bookService = instance;
        }
    }

    /**
     * The root model for search by example.
     */
    public Book getBook() {
        return book;
    }

    /**
     * The default search template.
     */
    public SearchTemplate getSearchTemplate() {
        return searchTemplate;
    }

    /**
     * Prepare the search parameters and call the bookService finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<Book> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchTemplate st = new SearchTemplate(getSearchTemplate());

        // total count so the paginator may display the total number of pages
        this.setRowCount(bookService.findCount(getBook(), st));

        // load one page of data 
        populateSearchTemplate(st, first, pageSize, sortField, sortOrder, filters);
        return bookService.find(getBook(), st);
    }
}