/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.yourcompany.yourproject.dao.more;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.yourcompany.yourproject.domain.more.MoreTypesDemo;
import com.yourcompany.yourproject.service.more.MoreTypesDemoGenerator;
import com.yourcompany.yourproject.dao.more.MoreTypesDemoDao;
import com.yourcompany.yourproject.util.*;

/**
 * Integration test on MoreTypesDemoDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class MoreTypesDemoDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(MoreTypesDemoDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private MoreTypesDemoDao moreTypesDemoDao;

    @Autowired
    private MoreTypesDemoGenerator moreTypesDemoGenerator;

    @Before
    public void onSetUp() throws Exception {
        //reset generator
        ValueGenerator.resetAll();
    }

    @Test
    public void testSaveAndGet() {
        MoreTypesDemo moreTypesDemo = moreTypesDemoGenerator.getMoreTypesDemo();

        // add it to a Set before saving
        Set<MoreTypesDemo> set = new HashSet<MoreTypesDemo>();
        set.add(moreTypesDemo);

        moreTypesDemoDao.save(moreTypesDemo);
        entityManager.flush();

        // reload it from cache and check equality
        MoreTypesDemo model = new MoreTypesDemo();
        model.setMoreTypesDemoId(moreTypesDemo.getMoreTypesDemoId());
        assertThat(moreTypesDemo).isEqualTo(moreTypesDemoDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(moreTypesDemo.getPrimaryKey()).isEqualTo(moreTypesDemoDao.get(model).getPrimaryKey());

        // but since you do not use a business key, equality is lost.
        assertThat(moreTypesDemo).isNotEqualTo(moreTypesDemoDao.get(model));
    }
}