/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.yourcompany.yourproject.dao.more;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.yourcompany.yourproject.dao.support.NamedQueryUtil;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.yourcompany.yourproject.domain.more.*;
import com.yourcompany.yourproject.util.*;

/**
 * Unit test on MoreTypesDemoDaoImpl
 */
public class MoreTypesDemoDaoImplTest {

    public MoreTypesDemoDaoImpl moreTypesDemoDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        moreTypesDemoDao = new MoreTypesDemoDaoImpl();
        moreTypesDemoDao.setEntityManager(entityManager);
        moreTypesDemoDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        MoreTypesDemo model = new MoreTypesDemo();
        model.setMoreTypesDemoId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(MoreTypesDemo.class), any())).thenReturn(model);

        MoreTypesDemo result = moreTypesDemoDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(MoreTypesDemo.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        MoreTypesDemo model = new MoreTypesDemo();
        model.setMoreTypesDemoId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(MoreTypesDemo.class), any())).thenReturn(null);

        MoreTypesDemo result = moreTypesDemoDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(MoreTypesDemo.class), any());
    }

    @Test
    public void testSave() {
        List<MoreTypesDemo> moreTypesDemos = new ArrayList<MoreTypesDemo>();
        moreTypesDemos.add(new MoreTypesDemo());
        moreTypesDemos.add(new MoreTypesDemo());

        moreTypesDemoDao.save(moreTypesDemos);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        MoreTypesDemo model1 = new MoreTypesDemo();
        model1.setMoreTypesDemoId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        MoreTypesDemo model2 = new MoreTypesDemo();
        model2.setMoreTypesDemoId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        List<MoreTypesDemo> moreTypesDemos = new ArrayList<MoreTypesDemo>();
        moreTypesDemos.add(model1);
        moreTypesDemos.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        moreTypesDemoDao.delete(moreTypesDemos);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        MoreTypesDemo model = new MoreTypesDemo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<MoreTypesDemo> moreTypesDemos = new ArrayList<MoreTypesDemo>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) moreTypesDemos);

        List<MoreTypesDemo> result = moreTypesDemoDao.find(model, searchTemplate);

        assertThat(result).isSameAs(moreTypesDemos);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        MoreTypesDemo model = new MoreTypesDemo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = moreTypesDemoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        MoreTypesDemo model = new MoreTypesDemo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, MoreTypesDemo.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = moreTypesDemoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        MoreTypesDemo model = new MoreTypesDemo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, MoreTypesDemo.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = moreTypesDemoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        moreTypesDemoDao.setCacheable(cacheable);
        moreTypesDemoDao.setCacheRegion(cacheRegion);

        SearchTemplate result = moreTypesDemoDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        moreTypesDemoDao.setCacheable(cacheable);
        moreTypesDemoDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = moreTypesDemoDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        moreTypesDemoDao.setCacheable(true);
        moreTypesDemoDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = moreTypesDemoDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}