/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-common:src/main/java/web/interceptor/AccountContextInterceptor.p.vm.java
 */
package com.yourcompany.yourproject.web.interceptor;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.HandlerInterceptor;

import com.yourcompany.yourproject.context.AccountContext;
import com.yourcompany.yourproject.web.context.AccountContextSupport;

/**
 * This interceptor is responsible for setting up the accountContext on the current thread of
 * execution and pass it to the view using the ModelMap.
 */
@Service
public class AccountContextInterceptor implements HandlerInterceptor {

    @Autowired
    private AccountContextSupport accountContextSupport;

    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
            throws ServletException {
        // Setup AccountContext and Log Context
        accountContextSupport.processAccountContext(request);

        // Give access to the current account context to the view
        // Note: using the modelAndView in the postHandle would not work
        //       in view returned by Spring Web Flow
        request.setAttribute("accountContext", AccountContext.getAccountContext());

        // proceed
        return true;
    }

    public void postHandle(HttpServletRequest request, HttpServletResponse response, Object handler,
            ModelAndView modelAndView) {
    }

    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex)
            throws Exception {
        accountContextSupport.resetContext();
    }
}