/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/NamedQueryUtilTest.p.vm.java
 */
package com.yourcompany.yourproject.dao.hibernate;

import java.util.*;

import org.apache.log4j.Logger;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.yourcompany.yourproject.dao.support.*;
import com.yourcompany.yourproject.util.*;
import com.yourcompany.yourproject.context.*;
import com.yourcompany.yourproject.domain.Account;
import com.yourcompany.yourproject.domain.Address;
import com.yourcompany.yourproject.domain.Book;
import com.yourcompany.yourproject.domain.ContactInfo;
import com.yourcompany.yourproject.domain.Document;
import com.yourcompany.yourproject.domain.Legacy;
import com.yourcompany.yourproject.domain.more.MoreTypesDemo;
import com.yourcompany.yourproject.domain.Role;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class NamedQueryUtilTest {

    private static final Logger logger = Logger.getLogger(NamedQueryUtilTest.class);

    @Autowired
    private NamedQueryUtil namedQueryUtil;

    @Test
    @SuppressWarnings("unchecked")
    public void executeQetAllAccountsQueryName() {
        String sqlQuery = "Account.selectAll";
        List<Account> accounts = (List<Account>) namedQueryUtil.findByNamedQuery(new SearchTemplate()
                .setNamedQuery(sqlQuery));

        if (accounts != null) {
            logger.info(accounts.size());

            for (Account account : accounts) {
                logger.info(account.toString());
            }
        }
    }

    @Test
    @SuppressWarnings("unchecked")
    public void executeGetAllAccountsSqlQuery() {
        String sqlQuery = "Account.selectAll.native";
        List<Account> accounts = (List<Account>) namedQueryUtil.findByNamedQuery(new SearchTemplate()
                .setNamedQuery(sqlQuery));

        if (accounts != null) {
            logger.info(accounts.size());
            for (Account account : accounts) {
                logger.info(account.toString());
            }
        }
    }

}