/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.yourcompany.yourproject.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.yourcompany.yourproject.domain.Account;
import com.yourcompany.yourproject.service.AccountServiceImpl;
import com.yourcompany.yourproject.dao.AccountDao;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

/**
 * Unit test on AccountServiceImpl
 */
public class AccountServiceImplTest {

    private AccountServiceImpl accountServiceImpl;
    private AccountDao accountDao;

    @Before
    public void setUp() {
        // called before each test.
        accountServiceImpl = new AccountServiceImpl();
        accountDao = mock(AccountDao.class);
        accountServiceImpl.setAccountDao(accountDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Account> none = new ArrayList<Account>();

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(none);

        Account result = accountServiceImpl.findUniqueOrNone(new Account());

        assertThat(result).isNull();
        verify(accountDao, times(1)).find(any(Account.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Account> unique = new ArrayList<Account>();
        unique.add(new Account());

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(unique);

        Account result = accountServiceImpl.findUniqueOrNone(new Account());

        assertThat(result).isNotNull();
        verify(accountDao, times(1)).find(any(Account.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Account> multiple = new ArrayList<Account>();
        multiple.add(new Account());
        multiple.add(new Account());

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(multiple);

        accountServiceImpl.findUniqueOrNone(new Account());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Account> none = new ArrayList<Account>();

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(none);

        accountServiceImpl.findUnique(new Account());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Account> unique = new ArrayList<Account>();
        unique.add(new Account());

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(unique);

        Account result = accountServiceImpl.findUnique(new Account());

        assertThat(result).isNotNull();
        verify(accountDao, times(1)).find(any(Account.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Account> multiple = new ArrayList<Account>();
        multiple.add(new Account());
        multiple.add(new Account());

        when(accountDao.find(any(Account.class), any(SearchTemplate.class))).thenReturn(multiple);

        accountServiceImpl.findUnique(new Account());
    }
}