/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.yourcompany.yourproject.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.yourcompany.yourproject.domain.Address;
import com.yourcompany.yourproject.service.AddressServiceImpl;
import com.yourcompany.yourproject.dao.AddressDao;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

/**
 * Unit test on AddressServiceImpl
 */
public class AddressServiceImplTest {

    private AddressServiceImpl addressServiceImpl;
    private AddressDao addressDao;

    @Before
    public void setUp() {
        // called before each test.
        addressServiceImpl = new AddressServiceImpl();
        addressDao = mock(AddressDao.class);
        addressServiceImpl.setAddressDao(addressDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Address> none = new ArrayList<Address>();

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(none);

        Address result = addressServiceImpl.findUniqueOrNone(new Address());

        assertThat(result).isNull();
        verify(addressDao, times(1)).find(any(Address.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Address> unique = new ArrayList<Address>();
        unique.add(new Address());

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(unique);

        Address result = addressServiceImpl.findUniqueOrNone(new Address());

        assertThat(result).isNotNull();
        verify(addressDao, times(1)).find(any(Address.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Address> multiple = new ArrayList<Address>();
        multiple.add(new Address());
        multiple.add(new Address());

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(multiple);

        addressServiceImpl.findUniqueOrNone(new Address());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Address> none = new ArrayList<Address>();

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(none);

        addressServiceImpl.findUnique(new Address());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Address> unique = new ArrayList<Address>();
        unique.add(new Address());

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(unique);

        Address result = addressServiceImpl.findUnique(new Address());

        assertThat(result).isNotNull();
        verify(addressDao, times(1)).find(any(Address.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Address> multiple = new ArrayList<Address>();
        multiple.add(new Address());
        multiple.add(new Address());

        when(addressDao.find(any(Address.class), any(SearchTemplate.class))).thenReturn(multiple);

        addressServiceImpl.findUnique(new Address());
    }
}