/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.yourcompany.yourproject.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.yourcompany.yourproject.domain.Document;
import com.yourcompany.yourproject.service.DocumentServiceImpl;
import com.yourcompany.yourproject.dao.DocumentDao;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

/**
 * Unit test on DocumentServiceImpl
 */
public class DocumentServiceImplTest {

    private DocumentServiceImpl documentServiceImpl;
    private DocumentDao documentDao;

    @Before
    public void setUp() {
        // called before each test.
        documentServiceImpl = new DocumentServiceImpl();
        documentDao = mock(DocumentDao.class);
        documentServiceImpl.setDocumentDao(documentDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Document> none = new ArrayList<Document>();

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(none);

        Document result = documentServiceImpl.findUniqueOrNone(new Document());

        assertThat(result).isNull();
        verify(documentDao, times(1)).find(any(Document.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Document> unique = new ArrayList<Document>();
        unique.add(new Document());

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(unique);

        Document result = documentServiceImpl.findUniqueOrNone(new Document());

        assertThat(result).isNotNull();
        verify(documentDao, times(1)).find(any(Document.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Document> multiple = new ArrayList<Document>();
        multiple.add(new Document());
        multiple.add(new Document());

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(multiple);

        documentServiceImpl.findUniqueOrNone(new Document());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Document> none = new ArrayList<Document>();

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(none);

        documentServiceImpl.findUnique(new Document());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Document> unique = new ArrayList<Document>();
        unique.add(new Document());

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(unique);

        Document result = documentServiceImpl.findUnique(new Document());

        assertThat(result).isNotNull();
        verify(documentDao, times(1)).find(any(Document.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Document> multiple = new ArrayList<Document>();
        multiple.add(new Document());
        multiple.add(new Document());

        when(documentDao.find(any(Document.class), any(SearchTemplate.class))).thenReturn(multiple);

        documentServiceImpl.findUnique(new Document());
    }
}