/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ModelGenerator.e.vm.java
 */
package com.yourcompany.yourproject.service;

import java.util.*;

import com.yourcompany.yourproject.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.yourcompany.yourproject.domain.Legacy;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class LegacyGenerator {

    /**
     * Returns a new Legacy instance filled with random values.
     */
    public Legacy getLegacy() {
        Legacy legacy = new Legacy();

        legacy.setCode(ValueGenerator.getUniqueString(8));
        legacy.setDept(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));
        legacy.setName(ValueGenerator.getUniqueString(16));
        // simple attributes follows
        legacy.setExtraInfo("d");
        return legacy;
    }

}