/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.yourcompany.yourproject.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.yourcompany.yourproject.domain.Role;
import com.yourcompany.yourproject.service.RoleServiceImpl;
import com.yourcompany.yourproject.dao.RoleDao;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

/**
 * Unit test on RoleServiceImpl
 */
public class RoleServiceImplTest {

    private RoleServiceImpl roleServiceImpl;
    private RoleDao roleDao;

    @Before
    public void setUp() {
        // called before each test.
        roleServiceImpl = new RoleServiceImpl();
        roleDao = mock(RoleDao.class);
        roleServiceImpl.setRoleDao(roleDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Role> none = new ArrayList<Role>();

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(none);

        Role result = roleServiceImpl.findUniqueOrNone(new Role());

        assertThat(result).isNull();
        verify(roleDao, times(1)).find(any(Role.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Role> unique = new ArrayList<Role>();
        unique.add(new Role());

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(unique);

        Role result = roleServiceImpl.findUniqueOrNone(new Role());

        assertThat(result).isNotNull();
        verify(roleDao, times(1)).find(any(Role.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Role> multiple = new ArrayList<Role>();
        multiple.add(new Role());
        multiple.add(new Role());

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(multiple);

        roleServiceImpl.findUniqueOrNone(new Role());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Role> none = new ArrayList<Role>();

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(none);

        roleServiceImpl.findUnique(new Role());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Role> unique = new ArrayList<Role>();
        unique.add(new Role());

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(unique);

        Role result = roleServiceImpl.findUnique(new Role());

        assertThat(result).isNotNull();
        verify(roleDao, times(1)).find(any(Role.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Role> multiple = new ArrayList<Role>();
        multiple.add(new Role());
        multiple.add(new Role());

        when(roleDao.find(any(Role.class), any(SearchTemplate.class))).thenReturn(multiple);

        roleServiceImpl.findUnique(new Role());
    }
}