/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.yourcompany.yourproject.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.yourcompany.yourproject.dao.support.NamedQueryUtil;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.yourcompany.yourproject.domain.*;
import com.yourcompany.yourproject.util.*;

/**
 * Unit test on AccountDaoImpl
 */
public class AccountDaoImplTest {

    public AccountDaoImpl accountDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        accountDao = new AccountDaoImpl();
        accountDao.setEntityManager(entityManager);
        accountDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        Account model = new Account();
        model.setAccountId(ValueGenerator.getUniqueString(32));

        when(entityManager.find(eq(Account.class), any())).thenReturn(model);

        Account result = accountDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(Account.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        Account model = new Account();
        model.setAccountId(ValueGenerator.getUniqueString(32));

        when(entityManager.find(eq(Account.class), any())).thenReturn(null);

        Account result = accountDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(Account.class), any());
    }

    @Test
    public void testSave() {
        List<Account> accounts = new ArrayList<Account>();
        accounts.add(new Account());
        accounts.add(new Account());

        accountDao.save(accounts);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        Account model1 = new Account();
        model1.setAccountId(ValueGenerator.getUniqueString(32));

        Account model2 = new Account();
        model2.setAccountId(ValueGenerator.getUniqueString(32));

        List<Account> accounts = new ArrayList<Account>();
        accounts.add(model1);
        accounts.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        accountDao.delete(accounts);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        Account model = new Account();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<Account> accounts = new ArrayList<Account>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) accounts);

        List<Account> result = accountDao.find(model, searchTemplate);

        assertThat(result).isSameAs(accounts);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        Account model = new Account();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = accountDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        Account model = new Account();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Account.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = accountDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        Account model = new Account();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Account.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = accountDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        accountDao.setCacheable(cacheable);
        accountDao.setCacheRegion(cacheRegion);

        SearchTemplate result = accountDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        accountDao.setCacheable(cacheable);
        accountDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = accountDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        accountDao.setCacheable(true);
        accountDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = accountDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}