/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.yourcompany.yourproject.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.yourcompany.yourproject.dao.support.NamedQueryUtil;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.yourcompany.yourproject.domain.*;
import com.yourcompany.yourproject.util.*;

/**
 * Unit test on ContactInfoDaoImpl
 */
public class ContactInfoDaoImplTest {

    public ContactInfoDaoImpl contactInfoDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        contactInfoDao = new ContactInfoDaoImpl();
        contactInfoDao.setEntityManager(entityManager);
        contactInfoDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        ContactInfo model = new ContactInfo();
        model.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(ContactInfo.class), any())).thenReturn(model);

        ContactInfo result = contactInfoDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(ContactInfo.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        ContactInfo model = new ContactInfo();
        model.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(ContactInfo.class), any())).thenReturn(null);

        ContactInfo result = contactInfoDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(ContactInfo.class), any());
    }

    @Test
    public void testSave() {
        List<ContactInfo> contactInfos = new ArrayList<ContactInfo>();
        contactInfos.add(new ContactInfo());
        contactInfos.add(new ContactInfo());

        contactInfoDao.save(contactInfos);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        ContactInfo model1 = new ContactInfo();
        model1.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        ContactInfo model2 = new ContactInfo();
        model2.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        List<ContactInfo> contactInfos = new ArrayList<ContactInfo>();
        contactInfos.add(model1);
        contactInfos.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        contactInfoDao.delete(contactInfos);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        ContactInfo model = new ContactInfo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<ContactInfo> contactInfos = new ArrayList<ContactInfo>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) contactInfos);

        List<ContactInfo> result = contactInfoDao.find(model, searchTemplate);

        assertThat(result).isSameAs(contactInfos);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        ContactInfo model = new ContactInfo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = contactInfoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        ContactInfo model = new ContactInfo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, ContactInfo.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = contactInfoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        ContactInfo model = new ContactInfo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, ContactInfo.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = contactInfoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        contactInfoDao.setCacheable(cacheable);
        contactInfoDao.setCacheRegion(cacheRegion);

        SearchTemplate result = contactInfoDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        contactInfoDao.setCacheable(cacheable);
        contactInfoDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = contactInfoDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        contactInfoDao.setCacheable(true);
        contactInfoDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = contactInfoDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}