/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.yourcompany.yourproject.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.yourcompany.yourproject.dao.support.NamedQueryUtil;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.yourcompany.yourproject.domain.*;
import com.yourcompany.yourproject.util.*;

/**
 * Unit test on DocumentDaoImpl
 */
public class DocumentDaoImplTest {

    public DocumentDaoImpl documentDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        documentDao = new DocumentDaoImpl();
        documentDao.setEntityManager(entityManager);
        documentDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        Document model = new Document();
        model.setDocumentId(ValueGenerator.getUniqueString(32));

        when(entityManager.find(eq(Document.class), any())).thenReturn(model);

        Document result = documentDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(Document.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        Document model = new Document();
        model.setDocumentId(ValueGenerator.getUniqueString(32));

        when(entityManager.find(eq(Document.class), any())).thenReturn(null);

        Document result = documentDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(Document.class), any());
    }

    @Test
    public void testSave() {
        List<Document> documents = new ArrayList<Document>();
        documents.add(new Document());
        documents.add(new Document());

        documentDao.save(documents);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        Document model1 = new Document();
        model1.setDocumentId(ValueGenerator.getUniqueString(32));

        Document model2 = new Document();
        model2.setDocumentId(ValueGenerator.getUniqueString(32));

        List<Document> documents = new ArrayList<Document>();
        documents.add(model1);
        documents.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        documentDao.delete(documents);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        Document model = new Document();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<Document> documents = new ArrayList<Document>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) documents);

        List<Document> result = documentDao.find(model, searchTemplate);

        assertThat(result).isSameAs(documents);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        Document model = new Document();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = documentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        Document model = new Document();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Document.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = documentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        Document model = new Document();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Document.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = documentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        documentDao.setCacheable(cacheable);
        documentDao.setCacheRegion(cacheRegion);

        SearchTemplate result = documentDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        documentDao.setCacheable(cacheable);
        documentDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = documentDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        documentDao.setCacheable(true);
        documentDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = documentDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}