/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.yourcompany.yourproject.dao.more;

import org.springframework.stereotype.Repository;
import com.yourcompany.yourproject.dao.more.MoreTypesDemoDao;

import com.yourcompany.yourproject.domain.more.MoreTypesDemo;
import com.yourcompany.yourproject.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the MoreTypesDemo DAO interface.
 */
@Repository
public class MoreTypesDemoDaoImpl extends HibernateGenericDao<MoreTypesDemo, Integer> implements MoreTypesDemoDao {
    public MoreTypesDemoDaoImpl() {
        super(MoreTypesDemo.class);
    }
}