/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/domain/Enum.enum.vm.java
 */
package com.yourcompany.yourproject.domain.enums;

import com.yourcompany.yourproject.util.ResourcesUtil;

public enum CivilityEnum {
    MR, MS;

    public String getLabel() {
        return ResourcesUtil.getInstance().getProperty("CivilityEnum_" + name());
    }
}