/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-common:src/main/java/web/FlowDebugUtil.p.vm.java
 */
package com.yourcompany.yourproject.web.util;

import org.springframework.stereotype.Component;

/**
 * Use this bean from your flow to print debug message in the console.
 */
@Component("out")
public class FlowDebugUtil {

    public void print(String msg) {
        System.out.println("[flow debug] " + msg);
    }
}
