/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/TabBean.p.vm.java
 */
package com.yourcompany.yourproject.web.util;

import java.io.Serializable;

/**
 * Tracks the p:tabView active index.
 */
public class TabBean implements Serializable {
    private static final long serialVersionUID = 1L;

    int activeIndex = 0;

    public void setActiveIndex(int activeIndex) {
        this.activeIndex = activeIndex;
    }

    public int getActiveIndex() {
        return activeIndex;
    }
}
