/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/context/package-info.p.vm.java
 */
/**
 * Context are resources that can be accessed statically within the scope of the current {@link java.lang.Thread}.
 * They mostly use the {@link java.lang.ThreadLocal} storage pattern.
 */
package com.yourcompany.yourproject.context;