/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/SearchForm.e.vm.java
 */
package com.yourcompany.yourproject.web.domain.more;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.primefaces.model.SortOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.yourcompany.yourproject.dao.support.SearchTemplate;
import com.yourcompany.yourproject.dao.support.SearchMode;
import com.yourcompany.yourproject.dao.support.DateRange;
import com.yourcompany.yourproject.domain.more.MoreTypesDemo;
import com.yourcompany.yourproject.service.more.MoreTypesDemoService;
import com.yourcompany.yourproject.web.domain.support.GenericSearchForm;

/**
 * SearchForm for MoreTypesDemoService
 */
@Component
@Scope("session")
public class MoreTypesDemoSearchForm extends GenericSearchForm<MoreTypesDemo> implements Serializable {
    private static final long serialVersionUID = 1L;
    // make it static to avoid http://jira.springframework.org/browse/SWF-1224
    private static MoreTypesDemoService moreTypesDemoService;

    private MoreTypesDemo moreTypesDemo = new MoreTypesDemo();
    private SearchTemplate searchTemplate = new SearchTemplate().setSearchMode(SearchMode.ANYWHERE);
    private DateRange dateJavaTemporalDateRange = new DateRange("dateJavaTemporalDate");
    private DateRange dateJavaTemporalTimestampRange = new DateRange("dateJavaTemporalTimestamp");
    private DateRange dateJodaRange = new DateRange("dateJoda");
    private DateRange dateTimeJodaRange = new DateRange("dateTimeJoda");

    @Autowired
    public MoreTypesDemoSearchForm(MoreTypesDemoService instance) {
        if (moreTypesDemoService == null) {
            moreTypesDemoService = instance;
        }
    }

    /**
     * The root model for search by example.
     */
    public MoreTypesDemo getMoreTypesDemo() {
        return moreTypesDemo;
    }

    /**
     * The default search template.
     */
    public SearchTemplate getSearchTemplate() {
        return searchTemplate;
    }

    public DateRange getDateJavaTemporalDateRange() {
        return dateJavaTemporalDateRange;
    }

    public DateRange getDateJavaTemporalTimestampRange() {
        return dateJavaTemporalTimestampRange;
    }

    public DateRange getDateJodaRange() {
        return dateJodaRange;
    }

    public DateRange getDateTimeJodaRange() {
        return dateTimeJodaRange;
    }

    /**
     * Prepare the search parameters and call the moreTypesDemoService finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<MoreTypesDemo> load(int first, int pageSize, String sortField, SortOrder sortOrder,
            Map<String, String> filters) {
        SearchTemplate st = new SearchTemplate(getSearchTemplate());
        st.add(getDateJavaTemporalDateRange());
        st.add(getDateJavaTemporalTimestampRange());
        st.add(getDateJodaRange());
        st.add(getDateTimeJodaRange());

        // total count so the paginator may display the total number of pages
        this.setRowCount(moreTypesDemoService.findCount(getMoreTypesDemo(), st));

        // load one page of data 
        populateSearchTemplate(st, first, pageSize, sortField, sortOrder, filters);
        return moreTypesDemoService.find(getMoreTypesDemo(), st);
    }
}