/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/flow/AccountContextListener.p.vm.java
 */
package com.yourcompany.yourproject.web.flow;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.webflow.execution.FlowExecutionListenerAdapter;
import org.springframework.webflow.execution.RequestContext;

import com.yourcompany.yourproject.context.AccountContext;
import com.yourcompany.yourproject.web.context.AccountContextSupport;

@Component
public class AccountContextListener extends FlowExecutionListenerAdapter {

    @Autowired
    private AccountContextSupport accountContextSupport;

    public void requestSubmitted(RequestContext context) {
        accountContextSupport.processAccountContext((HttpServletRequest) context.getExternalContext()
                .getNativeRequest());
        ((HttpServletRequest) context.getExternalContext().getNativeRequest()).setAttribute("accountContext",
                AccountContext.getAccountContext());
    }

    public void requestProcessed(RequestContext context) {
        accountContextSupport.resetContext();
    }
}