/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-common:src/main/java/web/ApplicationConversionService.p.vm.java
 */
package com.yourcompany.yourproject.web.flow;

import org.springframework.faces.model.converter.FacesConversionService;
import org.springframework.stereotype.Component;

import com.yourcompany.yourproject.web.domain.StringToLegacyPk;

@Component("conversionService")
public class ApplicationConversionService extends FacesConversionService {

    @Override
    protected void addDefaultConverters() {
        super.addDefaultConverters();

        // register custom converters below
        addConverter(new StringToLegacyPk());
    }
}
