/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.yourcompany.yourproject.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.yourcompany.yourproject.dao.support.GenericDao;
import com.yourcompany.yourproject.service.support.GenericEntityServiceImpl;
import com.yourcompany.yourproject.domain.Address;
import com.yourcompany.yourproject.dao.AddressDao;

/**
 *
 * Default implementation of the {@link AddressService} interface
 * @see AddressService
 */
@Service("addressService")
public class AddressServiceImpl extends GenericEntityServiceImpl<Address, Integer> implements AddressService {

    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(AddressServiceImpl.class);

    protected AddressDao addressDao;

    @Autowired
    public void setAddressDao(AddressDao addressDao) {
        this.addressDao = addressDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Address, Integer> getDao() {
        return addressDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address getNew() {
        return new Address();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address getNewWithDefaults() {
        Address result = getNew();
        result.initDefaultValues();
        return result;
    }

}