/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.yourcompany.yourproject.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.yourcompany.yourproject.dao.support.GenericDao;
import com.yourcompany.yourproject.service.support.GenericEntityServiceImpl;
import com.yourcompany.yourproject.domain.Book;
import com.yourcompany.yourproject.dao.BookDao;

/**
 *
 * Default implementation of the {@link BookService} interface
 * @see BookService
 */
@Service("bookService")
public class BookServiceImpl extends GenericEntityServiceImpl<Book, Integer> implements BookService {

    private static final Logger logger = Logger.getLogger(BookServiceImpl.class);

    protected BookDao bookDao;

    @Autowired
    public void setBookDao(BookDao bookDao) {
        this.bookDao = bookDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Book, Integer> getDao() {
        return bookDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Book getNew() {
        return new Book();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Book getNewWithDefaults() {
        Book result = getNew();
        result.initDefaultValues();
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void delete(Book book) {
        if (book == null) {
            if (logger.isDebugEnabled()) {
                logger.debug("Skipping deletion for null model!");
            }

            return;
        }

        // remove the reference from the associated account
        if (book.getAccount() != null) {
            book.getAccount().removeBook(book);
        }

        super.delete(book);
    }
}