/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.yourcompany.yourproject.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.yourcompany.yourproject.dao.support.GenericDao;
import com.yourcompany.yourproject.service.support.GenericEntityServiceImpl;
import com.yourcompany.yourproject.domain.Document;
import com.yourcompany.yourproject.dao.DocumentDao;

/**
 *
 * Default implementation of the {@link DocumentService} interface
 * @see DocumentService
 */
@Service("documentService")
public class DocumentServiceImpl extends GenericEntityServiceImpl<Document, String> implements DocumentService {

    private static final Logger logger = Logger.getLogger(DocumentServiceImpl.class);

    protected DocumentDao documentDao;

    @Autowired
    public void setDocumentDao(DocumentDao documentDao) {
        this.documentDao = documentDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Document, String> getDao() {
        return documentDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Document getNew() {
        return new Document();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Document getNewWithDefaults() {
        Document result = getNew();
        result.initDefaultValues();
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void delete(Document document) {
        if (document == null) {
            if (logger.isDebugEnabled()) {
                logger.debug("Skipping deletion for null model!");
            }

            return;
        }

        // remove the reference from the associated account
        if (document.getAccount() != null) {
            document.getAccount().removeDocument(document);
        }

        super.delete(document);
    }
}