/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.yourcompany.yourproject.service.more;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.yourcompany.yourproject.dao.support.GenericDao;
import com.yourcompany.yourproject.service.support.GenericEntityServiceImpl;
import com.yourcompany.yourproject.domain.more.MoreTypesDemo;
import com.yourcompany.yourproject.dao.more.MoreTypesDemoDao;

/**
 *
 * Default implementation of the {@link MoreTypesDemoService} interface
 * @see MoreTypesDemoService
 */
@Service("moreTypesDemoService")
public class MoreTypesDemoServiceImpl extends GenericEntityServiceImpl<MoreTypesDemo, Integer> implements
        MoreTypesDemoService {

    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(MoreTypesDemoServiceImpl.class);

    protected MoreTypesDemoDao moreTypesDemoDao;

    @Autowired
    public void setMoreTypesDemoDao(MoreTypesDemoDao moreTypesDemoDao) {
        this.moreTypesDemoDao = moreTypesDemoDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<MoreTypesDemo, Integer> getDao() {
        return moreTypesDemoDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoreTypesDemo getNew() {
        return new MoreTypesDemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoreTypesDemo getNewWithDefaults() {
        MoreTypesDemo result = getNew();
        result.initDefaultValues();
        return result;
    }

}