/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/GenericSearchForm.p.vm.java
 */
package com.yourcompany.yourproject.web.domain.support;

import java.util.Map;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

import com.yourcompany.yourproject.dao.support.OrderByDirection;
import com.yourcompany.yourproject.dao.support.SearchTemplate;

/**
 * Base search form for JPA entities. It supports 'Server Side Pagination' using PrimeFaces LazyDataModel.
 */
public abstract class GenericSearchForm<E> extends LazyDataModel<E> {
    private static final long serialVersionUID = 1L;
    private E selectedRow;
    private boolean resetPaginator = true;

    /**
     * Call it from your flow when a 'search' event is received, 
     * store the result in your viewState and use it from your view.
     * @return the model expected by dataTable with lazy loading support.  
     */
    public LazyDataModel<E> getLazyDataModel() {
        resetPaginator = true;
        return this;
    }

    /**
     * Applies the passed parameters to the passed SearchTemplate.
     * Note: filters are not supported for the moment
     * @return the passed searchTemplate
     */
    protected SearchTemplate populateSearchTemplate(SearchTemplate st, int first, int pageSize, String sortField,
            SortOrder sortOrder, Map<String, String> filters) {
        st.setFirstResult(resetPaginator ? 0 : first);
        resetPaginator = false;

        st.setMaxResults(pageSize);
        if (sortField != null) {
            OrderByDirection obd = convert(sortOrder);
            st.setOrderBy(sortField, obd);
        }
        return st;
    }

    /**
     * Returns the currently selected row. To be called from your flow upon a "selectXxx" transition.
     */
    public E getSelectedRow() {
        return selectedRow;
    }

    /**
     * Set the currently selected row. To be called from your dataTable.
     */
    public void setSelectedRow(E selectedRow) {
        this.selectedRow = selectedRow;
    }

    /**
     * Convert PrimeFaces SortOrder to our OrderByDirection.
     */
    public static OrderByDirection convert(SortOrder ob) {
        switch (ob) {
        case DESCENDING:
            return OrderByDirection.DESC;
        default:
            return OrderByDirection.ASC;
        }
    }
}