/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/domain/Identifiable.p.vm.java
 */
package com.yourcompany.yourproject.domain;

import java.io.Serializable;

/**
 * By making entities implement this interface we can easily retrieve from the
 * generic DAO the identifier property of the entity.
 */
public interface Identifiable<PK extends Serializable> {

    /**
     * @return the primary key
     */
    PK getPrimaryKey();

    /**
     * Sets the primary key
     */
    void setPrimaryKey(PK id);

    /**
     * Helper method to know whether the primary key is set or not.
     * @return true if the primary key is set, false otherwise
     */
    boolean isPrimaryKeySet();
}