/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/domain/Entity.e.vm.java
 */
package com.yourcompany.yourproject.domain;

import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "`ROLE`")
@Cache(usage = NONSTRICT_READ_WRITE)
public class Role implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger logger = Logger.getLogger(Role.class);

    // Raw attributes
    private Integer roleId; // pk
    private String roleName; // unique (not null)

    // ---------------------------
    // Constructors
    // ---------------------------

    public Role() {
    }

    public Role(Integer primaryKey) {
        setPrimaryKey(primaryKey);
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------

    @Transient
    @XmlTransient
    public Integer getPrimaryKey() {
        return getRoleId();
    }

    public void setPrimaryKey(Integer roleId) {
        setRoleId(roleId);
    }

    @Transient
    @XmlTransient
    public boolean isPrimaryKeySet() {
        return isRoleIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [roleId] ------------------------

    @Column(name = "ROLE_ID", nullable = false, unique = true, precision = 10)
    @GeneratedValue
    @Id
    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Transient
    public boolean isRoleIdSet() {
        return roleId != null;
    }

    // -- [roleName] ------------------------

    @NotEmpty
    @Length(max = 255)
    @Column(name = "role_name", nullable = false, unique = true)
    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    // -----------------------------------------
    // Set defaults values
    // -----------------------------------------

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    // -----------------------------------------
    // equals and hashCode
    // -----------------------------------------

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object role) {
        if (this == role) {
            return true;
        }

        if (!(role instanceof Role)) {
            return false;
        }

        Role other = (Role) role;

        if (getRoleName() == null) {
            if (other.getRoleName() != null) {
                return false;
            }
        } else if (!getRoleName().equals(other.getRoleName())) {
            return false;
        }

        return true;
    }

    private volatile int previousHashCode = 0;

    /**
     * hashCode implementation using a business key.
     */
    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (getRoleName() != null ? getRoleName().hashCode() : 0);

        if (previousHashCode != 0 && previousHashCode != result) {
            logger.warn("DEVELOPER: hashCode has changed!."
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: "
                    + getClass().getCanonicalName());
        }

        previousHashCode = result;
        return result;
    }

    // -----------------------------------------
    // toString
    // -----------------------------------------

    /**
     * Construct a readable string representation for this Role instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        result.append("role.roleId=[").append(getRoleId()).append("]\n");
        result.append("role.roleName=[").append(getRoleName()).append("]\n");
        return result.toString();
    }
}