/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/util/DateUtil.p.vm.java
 */
package com.yourcompany.yourproject.util;

import java.util.Date;

public class DateUtil {

    /**
     * Compare 2 dates using seconds precision.
     * Useful for JPA equality concern when comparing Date from Java world (with millisec precision) with date
     * retrieved from Oracle (second precision only).
     */
    public static boolean equalsWithSecondPrecision(Date d1, Date d2) {
        String s1 = Long.toString(d1.getTime());
        String s2 = Long.toString(d2.getTime());
        s1 = s1.substring(0, s1.length() - 3);
        s2 = s2.substring(0, s2.length() - 3);
        return s1.equals(s2);
    }

    public static int hashCodeWithSecondPrecision(Date d1) {
        String s1 = Long.toString(d1.getTime());
        return s1.substring(0, s1.length() - 3).hashCode();
    }
}